### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dominathan** [1Power/answers#1]
1) questions_controller#show, views/questions/show.html.erb

@question is set in the show action by the private method, which is good.  You then set @answer = Answer.new, which is so you can leave an answer.  But when you go to the view/questions/show.html.erb, you do not render the partial that is to update the question.  You need to render partial: 'answers/form'.  Try that out and see what happens.  You will still need to verify that the answer is associated with that question. 

2) DB/models - Your answers needs to "belong_to" a question.  The way you do this is make sure it has an attribute, :question_id. Every time you save a new answer, the `answer.question_id = @question.id`.
I can help you walk through this if it doesn't make sense, but it's very important!!!!!! going forward.  

2) views/questions/show.html.erb
You list all the  ` @question.answers.each do |answer| ` .  However, I would do this in your controller#show. ` @answers = @question.answers `

If you still have questions with these let me know.

**Comment by 1Power** [comment]
Fulfilled requirements: https://basecamp.com/1940253/projects/7973405/messages/37129271

https://answers-app.herokuapp.com/
